default: &default
  adapter: <%= ENV.fetch("DATABASE_ADAPTER") { 'postgresql' } %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch('DATABASE_NAME') { 'asia_tech_database' }%>
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'asia' }%>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'asis-password' }%>
  host: <%= ENV.fetch('MASTER_DATABASE_HOSTNAME') { 'localhost' }%>
  port: <%= ENV.fetch('MASTER_DATABASE_PORT') { 5433 }%>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
